"""
Django settings for djangoproj project.
Generated by 'django-admin startproject'.
Docs: https://docs.djangoproject.com/en/5.2/topics/settings/
"""

import os
from pathlib import Path

# ──────────────── Core paths ────────────────
BASE_DIR = Path(__file__).resolve().parent.parent

# ──────────────── Security ────────────────
SECRET_KEY = "django-insecure-ccow$tz_=9%dxu4(0%^(z%nx32#s@(zt9$ih@)5l54yny)wm-0"
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    (
        "https://ryanwdear-8000.theiadockernext-0-labs-prod-"
        "theiak8s-4-tor01.proxy.cognitiveclass.ai"
    ),
]

CSRF_TRUSTED_ORIGINS = [
    "https://ryanwdear-8000.theiadockernext-0-labs-prod-"
    "theiak8s-4-tor01.proxy.cognitiveclass.ai"
]

# ──────────────── REST framework ────────────────
REST_FRAMEWORK = {"DEFAULT_AUTHENTICATION_CLASSES": []}

# ──────────────── Installed apps ────────────────
INSTALLED_APPS = [
    "djangoapp.apps.DjangoappConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# ──────────────── Middleware ────────────────
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "djangoproj.urls"

# ──────────────── Templates ────────────────
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "frontend" / "static",
            # uncomment the two lines below once you have a built front-end bundle
            # BASE_DIR / "frontend" / "build",
            # BASE_DIR / "frontend" / "build" / "static",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "djangoproj.wsgi.application"

# ──────────────── Database ────────────────
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ──────────────── Password validation ────────────────
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ──────────────── Internationalization ────────────────
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

# ──────────────── Static & media ────────────────
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"

STATICFILES_DIRS = [
    BASE_DIR / "frontend" / "static",
    # Once the front-end is built, restore these:
    # BASE_DIR / "frontend" / "build",
    # BASE_DIR / "frontend" / "build" / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = STATIC_ROOT / "media"

# ──────────────── Misc ────────────────
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
