# Generated by Django 5.2 on 2025-04-29 23:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('country', models.CharField(default='Unknown', max_length=50)),
                ('established_year', models.IntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2023)])),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('WAGON', 'Wagon'), ('TRUCK', 'Truck'), ('COUPE', 'Coupe'), ('CONVERTIBLE', 'Convertible')], default='SEDAN', max_length=20)),
                ('year', models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2023)])),
                ('dealer_id', models.IntegerField()),
                ('color', models.CharField(default='Unpainted', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=30000.0, max_digits=10)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.carmake')),
            ],
        ),
    ]
